@MediaFetch_HostAddress = http://127.0.0.1:5080
@JobId = 00000000-0000-0000-0000-000000000000

### Проверить метаданные
POST {{MediaFetch_HostAddress}}/api/media/inspect
Content-Type: application/json

{
  "url": "https://www.youtube.com/watch?v=REPLACE_ME"
}

### Скачать видео до 720p
POST {{MediaFetch_HostAddress}}/api/downloads
Content-Type: application/json

{
  "url": "https://www.youtube.com/watch?v=REPLACE_ME",
  "mode": "Video",
  "maxHeight": 720
}

### Извлечь MP3
POST {{MediaFetch_HostAddress}}/api/downloads
Content-Type: application/json

{
  "url": "https://www.youtube.com/watch?v=REPLACE_ME",
  "mode": "Audio",
  "audioFormat": "Mp3"
}

### Проверить состояние
GET {{MediaFetch_HostAddress}}/api/downloads/{{JobId}}

### Получить файл
GET {{MediaFetch_HostAddress}}/api/downloads/{{JobId}}/file

### Отменить задачу
DELETE {{MediaFetch_HostAddress}}/api/downloads/{{JobId}}
